---
title: "ACLU Child Separations"
output: html_notebook
---

```{r message=FALSE, warning=FALSE, error=TRUE}
# load libraries
library(readr)
library(dplyr)

```

```{r error=TRUE}
# load data
aclu <- read_csv(aclu.separations.csv)
```

```{r error=TRUE}
# inspect data
head(aclu, n)
summary(aclu, n)

```

```{r error=TRUE}
# select columns
aclu %>%
 select(-addr)
head(aclu)

```

```{r error=TRUE}
# view columns
names(aclu)
```

```{r error=TRUE}
# rename columns
aclu %>%
	rename(city = program_city,
        state = program state,
        number_children = n,
        longitude = lon,
        latitude = lat)
head(aclu)

```

```{r error=TRUE}
# add column
border_latitude <- 25.83

```

```{r error=TRUE}
# latitude change
aclu %>
	mutate(lat_change_border = (lat_change_border = latitude - border_latitude))



```

```{r error=TRUE}
# number of children
aclu %>%
	filter(lat_change_border > 15)
	arrange(desc(lat_change_border))
head(further_away)

aclu %>%
	arrange(desc(ordered_by_children))
head(ordered_by_children)

```

```{r error=TRUE}
# state analysis
chosen_state <- CA

alcu%>%
	filter(state == chosen_state)
	arrange(desc(number_children))
head(chosen_state_separations)



```